/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import control.counter;
import control.admClientes;

/**
 *
 * @author gmora
 */
public class Interfaz extends javax.swing.JFrame {
     private counter elCounter = new counter();
     private admClientes AdmClientes = new admClientes();
    // private counter controlCounter;

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        
        System.out.println(elCounter.agregarCasilleros(10));
        System.out.println(elCounter.toString());
        System.out.println("\n");
        initComponents();
        
        
    }
    
       

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lbltituloClientes = new javax.swing.JLabel();
        txtNombreCounter = new javax.swing.JTextField();
        txtIdCliente = new javax.swing.JTextField();
        lblNombreCounter = new javax.swing.JLabel();
        Cedula = new javax.swing.JLabel();
        txtDireccionCounter = new javax.swing.JTextField();
        btnClienteDireccion = new javax.swing.JLabel();
        txtNumCasillerosCounter = new javax.swing.JTextField();
        lblNumCasillerosCounter = new javax.swing.JLabel();
        BtnCounter = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taCounter = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbltituloClientes.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbltituloClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltituloClientes.setText("Counter");
        lbltituloClientes.setToolTipText("");

        txtNombreCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreCounterActionPerformed(evt);
            }
        });

        txtIdCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdClienteActionPerformed(evt);
            }
        });

        lblNombreCounter.setText("Nombre");

        Cedula.setText("Cedula");

        txtDireccionCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionCounterActionPerformed(evt);
            }
        });

        btnClienteDireccion.setText("Direccion");

        txtNumCasillerosCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumCasillerosCounterActionPerformed(evt);
            }
        });

        lblNumCasillerosCounter.setText("Numero de Casilleros");

        BtnCounter.setText("Agregar");
        BtnCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCounterActionPerformed(evt);
            }
        });

        taCounter.setColumns(20);
        taCounter.setRows(5);
        jScrollPane1.setViewportView(taCounter);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(260, Short.MAX_VALUE)
                .addComponent(lbltituloClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(352, 352, 352))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cedula)
                        .addGap(18, 18, 18)
                        .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClienteDireccion)
                            .addComponent(lblNombreCounter))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDireccionCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumCasillerosCounter)
                        .addGap(18, 18, 18)
                        .addComponent(txtNumCasillerosCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lbltituloClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cedula))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreCounter)
                    .addComponent(txtNombreCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClienteDireccion)
                    .addComponent(txtDireccionCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumCasillerosCounter)
                    .addComponent(txtNumCasillerosCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(BtnCounter)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txtNombreCounterActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
    }                                                

    private void txtIdClienteActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void txtDireccionCounterActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void txtNumCasillerosCounterActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void BtnCounterActionPerformed(java.awt.event.ActionEvent evt) {                                           
       
        
        String elNombre = txtNombreCounter.getText();
         String cedula=  txtIdCliente.getText() ;
        String direccion = txtDireccionCounter.getText();
        int numCasilleros= Integer.parseInt ( txtNumCasillerosCounter.getText() );
        
         elCounter = new counter( elNombre, cedula ,direccion, numCasilleros); 
         boolean agregarCasilleros = elCounter.agregarCasilleros(numCasilleros);
        taCounter.setText("Cliente agregado");
          
        FrSubMenu ventanaSubMenu = new FrSubMenu(new javax.swing.JDialog(), true);
        ventanaSubMenu.setVisible(true);
      
        
        
        
        
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Interfaz().setVisible(true);
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton BtnCounter;
    private javax.swing.JLabel Cedula;
    private javax.swing.JLabel btnClienteDireccion;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNombreCounter;
    private javax.swing.JLabel lblNumCasillerosCounter;
    private javax.swing.JLabel lbltituloClientes;
    private javax.swing.JTextArea taCounter;
    private javax.swing.JTextField txtDireccionCounter;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombreCounter;
    private javax.swing.JTextField txtNumCasillerosCounter;
    // End of variables declaration                   
}
